server:
  port: 8080 # Sisteme giriş noktası portu

spring:
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true # Servisleri Eureka üzerinden otomatik bulur

      default-filters:
        - AuthenticationFilter          
      routes:
        - id: auth-services
          uri: lb://AUTH-SERVICES
          predicates:
            - Path=/api/auth/**
            - Path=/api/admin/**
        - id: user-service
          uri: lb://USER-SERVICE
          predicates:
            - Path=/api/users/**
management:
  endpoints:
    web:
      # Hangi endpoint'lerin HTTP üzerinden erişilebilir olacağını belirtir
      exposure:
        # '*' tüm endpoint'leri açar (geliştirme için uygun)
        # Daha güvenli: include: health,info,gateway
        include: "*" 
  endpoint:
    # Gateway'e özel actuator endpoint'ini aktif et
    gateway:
      enabled: true            

jwt:
  secret: "Y29rLWd1Y2x1LWJpci1zaWZyZS1idS1raW1zZS1iaWxlbWV6LTEyMzQ1IQ===="

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/