server:
  port: 8080

spring:
  cloud:
    gateway:
      discovery:
        locator:
          enabled: false
      
      # 👇 YENİ EKLENEN KISIM: CORS AYARLARI BURADA OLMALI 👇
      globalcors:
        cors-configurations:
          '[/**]':
            allowedOrigins: "http://localhost:5173" # Frontend Adresin
            allowedMethods:
              - GET
              - POST
              - PUT
              - DELETE
              - OPTIONS
              - PATCH
            allowedHeaders: "*"
            allowCredentials: true
      # 👆 BİTİŞ 👆

      default-filters:
        - name: AuthenticationFilter
      routes:
        # 1. Kulüp Admin Yolu (En yüksek öncelik)
        - id: club-admin
          uri: lb://CLUB-SERVICE
          predicates:
            - Path=/api/admin/clubs/** order: 1

        # 2. Kulüp Public Yolu
        - id: club-service
          uri: lb://CLUB-SERVICE
          predicates:
            - Path=/api/clubs/** order: 2

        # 3. Auth Admin Yolu
        - id: auth-admin
          uri: lb://AUTH-SERVICES
          predicates:
            - Path=/api/admin/** order: 3

        # 4. Auth Public Yolu
        - id: auth-services
          uri: lb://AUTH-SERVICES
          predicates:
            - Path=/api/auth/** order: 4

        # 5. User Servisi
        - id: user-service
          uri: lb://USER-SERVICE
          predicates:
            - Path=/api/users/**
          order: 5

          # --- EVENT SERVİSİ ---
        - id: event-service
          uri: lb://EVENT-SERVICE 
          predicates:
            - Path=/api/events/** order: 6

        - id: course-service
          uri: lb://course-service  
          predicates:
            - Path=/api/courses/** order: 7

        - id: assignment-service
          uri: lb://assignment-service
          predicates:
            - Path=/api/assignments/**
          order: 8  

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    gateway:
      enabled: true

jwt:
  secret: "Base64:jZwU5GubnUxm1GesQMzbti2lhVckdkLpww1Awn3h0ng="

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/