server:
  port: 8080

spring:
  cloud:
    gateway:
      discovery:
        locator:
          enabled: false
      default-filters:
        - name: AuthenticationFilter
      routes:
        - id: auth-services
          uri: lb://AUTH-SERVICES
          predicates:
            - Path=/api/auth/**, /api/admin/**
        - id: user-service
          uri: lb://USER-SERVICE
          predicates:
            - Path=/api/users/**
        - id: club-service
          uri: lb://CLUB-SERVICE 
          predicates:
            - Path=/api/clubs/** # Öğrenci/public yolları
            - Path=/api/admin/clubs/** # Admin yolları
    

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    gateway:
      enabled: true

# Geçerli bir Base64 (en az 32 byte) key ile değiştirin
jwt.secret: "Base64:jZwU5GubnUxm1GesQMzbti2lhVckdkLpww1Awn3h0ng="
  

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/

