server:
  port: 8080

spring:
  cloud:
    gateway:
      discovery:
        locator:
          enabled: false
      default-filters:
        - name: AuthenticationFilter
      routes:
        # 1. KULÜP SERVİSİ (Spesifik yol)
        - id: club-service
          uri: lb://CLUB-SERVICE # Eureka'daki adınızla eşleşmeli
          predicates:
            - Path=/api/clubs/** # Public yol
            - Path=/api/admin/clubs/** # Admin yolu
          # --- YENİ EKLEME ---
          order: 1  # YÜKSEK ÖNCELİK (Küçük sayı)

        # 2. AUTH SERVİSİ (Genel yol)
        - id: auth-services
          uri: lb://AUTH-SERVICES # Eureka'daki adınızla eşleşmeli
          predicates:
            - Path=/api/auth/** # Public yol
            - Path=/api/admin/** # Admin yolu (Genel)
          # --- YENİ EKLEME ---
          order: 2  # DÜŞÜK ÖNCELİK (Büyük sayı)

        # 3. USER SERVİSİ (Diğerleriyle çakışmıyor)
        - id: user-service
          uri: lb://USER-SERVICE
          predicates:
            - Path=/api/users/**
          order: 3  # (Buna da bir sıra verelim)
    

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    gateway:
      enabled: true

# Geçerli bir Base64 (en az 32 byte) key ile değiştirin
jwt.secret: "Base64:jZwU5GubnUxm1GesQMzbti2lhVckdkLpww1Awn3h0ng="
  

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/

