server:
  port: 8080

spring:
  cloud:
    gateway:
      discovery:
        locator:
          enabled: false
      
      globalcors:
        cors-configurations:
          '[/**]':
            allowedOrigins: "http://localhost:5173"
            allowedMethods:
              - GET
              - POST
              - PUT
              - DELETE
              - OPTIONS
              - PATCH
            allowedHeaders: "*"
            allowCredentials: true

      default-filters:
        - name: AuthenticationFilter
        # 👇 SİHİRLİ DOKUNUŞ BURADA 👇
        - name: DedupeResponseHeader
          args:
            strategy: RETAIN_UNIQUE
            name: Access-Control-Allow-Origin Access-Control-Allow-Credentials

      routes:
        # ... (Senin mevcut rotaların aynen kalacak) ...
        # ... club-admin, club-service, auth, user, event, course, assignment ...
        # (Aşağıdaki kodları değiştirmene gerek yok, sadece default-filters'ı güncellemen yeterli)
        - id: club-admin
          uri: lb://CLUB-SERVICE
          predicates:
            - Path=/api/admin/clubs/**
          order: 1
          
        - id: club-service
          uri: lb://CLUB-SERVICE
          predicates:
            - Path=/api/clubs/**
          order: 2

        - id: auth-admin
          uri: lb://AUTH-SERVICES
          predicates:
            - Path=/api/admin/**
          order: 3

        - id: auth-services
          uri: lb://AUTH-SERVICES
          predicates:
            - Path=/api/auth/**
          order: 4

        - id: user-service
          uri: lb://USER-SERVICE
          predicates:
            - Path=/api/users/**
          order: 5

        - id: event-service
          uri: lb://EVENT-SERVICE 
          predicates:
            - Path=/api/events/**
          order: 6

        - id: course-service
          uri: lb://course-service  
          predicates:
            - Path=/api/courses/**
          order: 7

        - id: assignment-service
          uri: lb://assignment-service
          predicates:
            - Path=/api/assignments/**
          order: 8  

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    gateway:
      enabled: true

jwt:
  secret: "Base64:jZwU5GubnUxm1GesQMzbti2lhVckdkLpww1Awn3h0ng="

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/