server:
  port: 8080

spring:
  cloud:
    gateway:
      discovery:
        locator:
          enabled: false
      default-filters:
        - name: AuthenticationFilter
      routes:
        # 1. Kulüp Admin Yolu (En yüksek öncelik)
        - id: club-admin
          uri: lb://CLUB-SERVICE
          predicates:
            - Path=/api/admin/clubs/**  # Sadece admin kulüp yolu
          order: 1

        # 2. Kulüp Public Yolu
        - id: club-service
          uri: lb://CLUB-SERVICE
          predicates:
            - Path=/api/clubs/**  # Public kulüp yolu
          order: 2

        # 3. Auth Admin Yolu (Genel admin işlemleri)
        - id: auth-admin
          uri: lb://AUTH-SERVICES
          predicates:
            - Path=/api/admin/**  # Diğer admin endpoint'leri
          order: 3

        # 4. Auth Public Yolu
        - id: auth-services
          uri: lb://AUTH-SERVICES
          predicates:
            - Path=/api/auth/**  # Public auth yolu
          order: 4

        # 5. User Servisi
        - id: user-service
          uri: lb://USER-SERVICE
          predicates:
            - Path=/api/users/**
          order: 5

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    gateway:
      enabled: true

jwt:
  secret: "Base64:jZwU5GubnUxm1GesQMzbti2lhVckdkLpww1Awn3h0ng="

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
