server:
  port: 9005

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/assignment_db
    username: your_username
    password: your_password
  jpa:
    hibernate:
      ddl-auto: update
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/