server:
  port: 9005

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/assignment_db
    username: eduadmin 
    password: edu123
  jpa:
    hibernate:
      ddl-auto: update
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
    minio:
     url: http://localhost:9000
     access-key: your_minio_user     # docker-compose'da belirlediğiniz kullanıcı adı
     secret-key: your_minio_password # docker-compose'da belirlediğiniz şifre
     bucket:
     name: educonnect # Kullanacağınız varsayılan bucket adı

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/