server:
  port: 9001

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres?currentSchema=auth_db
    username: eduadmin
    password: edu123
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        default_schema: auth_db

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
