server:
  port: 9002

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres?currentSchema=auth_db
    username: eduadmin
    password: edu123
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        default_schema: auth_db

  rabbitmq:
    host: localhost # Docker'daki RabbitMQ servisi
    port: 5672
    username: guest
    password: guest

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/

jwt:
  secret: "Y29rLWd1Y2x1LWJpci1zaWZyZS1idS1raW1zZS1iaWxlbWV6LTEyMzQ1IQ===="
  
  expiration-ms: 86400000 
    
