server:
  port: 9007

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/badge_db
    username: your_username
    password: your_password
  jpa:
    hibernate:
      ddl-auto: update

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/