server:
  port: 9005

spring:
  application:
    name: club-service
    
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres?currentSchema=club_db
    username: eduadmin
    password: edu123
    driver-class-name: org.postgresql.Driver
    
  jpa:
    hibernate:
      ddl-auto: none
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true # Geliştirme aşamasında SQL sorgularını görmek iyidir

  # RabbitMQ ayarları 'spring' bloğunun altına taşındı
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest


# MinIO ayarları (Custom property olduğu için en dışta kalabilir)
minio:
  url: http://localhost:9000
  access-key: your_minio_user     # Kendi MinIO kullanıcı adınız
  secret-key: your_minio_password # Kendi MinIO şifreniz
  bucket:
    name: club-bucket

jwt:
  secret: "Base64:jZwU5GubnUxm1GesQMzbti2lhVckdkLpww1Awn3h0ng="

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/