server:
  port: 9005 # (9001, 9002, 9004 kullanıldı, 9005 uygun görünüyor)

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres?currentSchema=club_db
    username: eduadmin
    password: edu123
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update # Başlangıçta tabloları oluştur
  cloud:
    gateway:
      routes:
        - id: club-service
          uri: lb://CLUB-SERVICE
          predicates:
            - Path=/api/clubs/**
            - Path=/api/admin/clubs/**    

  # Kulüp logolarını yüklemek için MinIO ayarları
minio:
  url: http://localhost:9000
  access-key: your_minio_user
  secret-key: your_minio_password
  bucket:
    name: club-bucket # Veya kulüp logoları için 'club-logos' adında ayrı bir bucket

rabbitmq:
  host: localhost # Docker'daki RabbitMQ'ya 'localhost' üzerinden bağlanır
  port: 5672
  username: guest
  password: guest

  # JPA'nın veritabanı ile (PostgreSQL) nasıl konuşacağını belirtir
  database-platform: org.hibernate.dialect.PostgreSQLDialect

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
