server:
  port: 9006 # Diğer servislerle çakışmayan bir port

spring:
  # Veritabanı Bağlantısı
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres?currentSchema="event_db" # Docker'daki PostgreSQL'e 'localhost' üzerinden bağlanır
    username: eduadmin
    password: edu123
    driver-class-name: org.postgresql.Driver
  
  # JPA ve Veritabanı Ayarları
  jpa:
    hibernate:
      ddl-auto: update # Geliştirme aşamasında şemayı otomatik günceller
      default_schema: "event_db"
    show-sql: true # Çalışan SQL sorgularını konsolda gösterir
  
  # Mesaj Kuyruğu Bağlantısı
  rabbitmq:
    host: localhost # Docker'daki RabbitMQ'ya 'localhost' üzerinden bağlanır
    port: 5672
    username: guest
    password: guest

minio:
  url: http://localhost:9000
  access-key: your_minio_user     # docker-compose'da belirlediğiniz kullanıcı adı
  secret-key: your_minio_password # docker-compose'da belirlediğiniz şifre
  bucket:
    name: events-bucket # Kullanacağınız varsayılan bucket adı

jwt:
  secret: "Base64:jZwU5GubnUxm1GesQMzbti2lhVckdkLpww1Awn3h0ng="

# Eureka Server'a Kayıt
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/

# Not: PostgreSQL'de "event_db" adında yeni bir veritabanı oluşturmanız gerekecektir.