server:
  port: 9008

spring:
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
  mail:
    host: smtp.gmail.com # veya kendi mail sunucunuz
    port: 587
    username: your-email@gmail.com
    password: your-app-password # Gmail için uygulama şifresi
    properties:
      mail.smtp.auth: true
      mail.smtp.starttls.enable: true

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/