server:
  port: 9008

spring:
  application:
    name: notification-service

  # RabbitMQ Bağlantısı
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest

  # E-Posta Ayarları (Mailpit - Development)
  mail:
    host: localhost
    port: 1025
    username: ""
    password: ""
    properties:
      mail:
        smtp:
          auth: false
          starttls:
            enable: false
    test-connection: false

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/

# Custom property for from address
app:
  mail:
    from: noreply@educonnect.com
