server:
  port: 9002
spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/user_db # DİKKAT: 'postgres' yerine 'localhost'
    username: eduadmin
    password: edu123
  redis:
    host: localhost # DİKKAT: 'redis' yerine 'localhost'
    port: 6379
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/