server:
  port: 9002
spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/user_db # DİKKAT: 'postgres' yerine 'localhost'
    username: eduadmin
    password: edu123
  redis:
    host: localhost # DİKKAT: 'redis' yerine 'localhost'
    port: 6379
    minio:
    url: http://localhost:9000
    access-key: your_minio_user     # docker-compose'da belirlediğiniz kullanıcı adı
    secret-key: your_minio_password # docker-compose'da belirlediğiniz şifre
    bucket:
    name: educonnect # Kullanacağınız varsayılan bucket adı
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/