server:
  port: 9003

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres?currentSchema=user_db
    username: eduadmin
    password: edu123
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        default_schema: user_db
        dialect: org.hibernate.dialect.PostgreSQLDialect

  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest      

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
